


package com.legstar.test.coxb.tcobwvb.bind;

import com.legstar.coxb.ICobolBinding;
import com.legstar.coxb.common.CComplexBinding;
import com.legstar.coxb.ICobolStringBinding;
import com.legstar.coxb.CobolBindingFactory;
import com.legstar.coxb.ICobolBindingFactory;
import com.legstar.coxb.ICobolComplexBinding;
import com.legstar.coxb.host.HostException;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import com.legstar.test.coxb.tcobwvb.Filler12;
import com.legstar.test.coxb.tcobwvb.ObjectFactory;

/**
 * LegStar Binding for Complex element :
 *   Filler12.
 * 
 * This class was generated by LegStar Binding generator.
 */
public class Filler12Binding 
             extends CComplexBinding {

    /** Value object to which this cobol complex element is bound. */
    private Filler12 mValueObject;
  
    /** Indicates that the associated Value object just came from the constructor
     * and doesn't need to be recreated. */
    private boolean mUnusedValueObject = false;
    
    /** Maximum host bytes size for this complex object. */
    private static final int BYTE_LENGTH = 8;
    
    /** Child bound to value object property LastTransDay(String). */
    public ICobolStringBinding _lastTransDay;
    /** Child bound to value object property Filler14(String). */
    public ICobolStringBinding _filler14;
    /** Child bound to value object property LastTransMonth(String). */
    public ICobolStringBinding _lastTransMonth;
    /** Child bound to value object property Filler16(String). */
    public ICobolStringBinding _filler16;
    /** Child bound to value object property LastTransYear(String). */
    public ICobolStringBinding _lastTransYear;
            
    /** Logger. */
    private final Log _log = LogFactory.getLog(getClass());

    /** Binding factory. */
    private static final ICobolBindingFactory BF
        = CobolBindingFactory.getBindingFactory();
 
    /** Static reference to Value object factory to be used as default. */
    private static final ObjectFactory JF = new ObjectFactory();
    
    /** Current Value object factory (Defaults to the static one but can be
     *  changed). */
    private ObjectFactory mValueObjectFactory = JF;
    
    /**
     * Constructor for a root Complex element without a bound Value object.
     */
    public Filler12Binding() {
        this(null);
    }

    /**
     * Constructor for a root Complex element with a bound Value object.
     * 
     * @param valueObject the concrete Value object instance bound to this
     *        complex element
     */
    public Filler12Binding(
            final Filler12 valueObject) {
        this("", "", null, valueObject);
    }

    /**
    * Constructor for a Complex element as a child of another element and
    * an associated Value object.
    * 
    * @param bindingName the identifier for this binding
    * @param fieldName field name in parent Value object
    * @param valueObject the concrete Value object instance bound to this
    *        complex element
    * @param parentBinding a reference to the parent binding
    */
    public Filler12Binding(
            final String bindingName,
            final String fieldName,
            final ICobolComplexBinding parentBinding,
            final Filler12 valueObject) {
        
        super(bindingName, fieldName, Filler12.class, null, parentBinding);
        mValueObject = valueObject;
        if (mValueObject != null) {
            mUnusedValueObject = true;
        }
        initChildren();
        setByteLength(BYTE_LENGTH);
    }

    /** Creates a binding property for each child. */
    private void initChildren() {
        if (_log.isDebugEnabled()) {
            _log.debug("Initializing started");
        }
        /* Create binding children instances */

        _lastTransDay = BF.createStringBinding("LastTransDay",
               "LastTransDay", String.class, this);
        _lastTransDay.setCobolName("LAST-TRANS-DAY");
        _lastTransDay.setByteLength(2);
        _filler14 = BF.createStringBinding("Filler14",
               "Filler14", String.class, this);
        _filler14.setCobolName("FILLER");
        _filler14.setByteLength(1);
        _lastTransMonth = BF.createStringBinding("LastTransMonth",
               "LastTransMonth", String.class, this);
        _lastTransMonth.setCobolName("LAST-TRANS-MONTH");
        _lastTransMonth.setByteLength(2);
        _filler16 = BF.createStringBinding("Filler16",
               "Filler16", String.class, this);
        _filler16.setCobolName("FILLER");
        _filler16.setByteLength(1);
        _lastTransYear = BF.createStringBinding("LastTransYear",
               "LastTransYear", String.class, this);
        _lastTransYear.setCobolName("LAST-TRANS-YEAR");
        _lastTransYear.setByteLength(2);

        /* Add children to children list */
        getChildrenList().add(_lastTransDay);
        getChildrenList().add(_filler14);
        getChildrenList().add(_lastTransMonth);
        getChildrenList().add(_filler16);
        getChildrenList().add(_lastTransYear);
 
        if (_log.isDebugEnabled()) {
            _log.debug("Initializing successful");
        }
    }
    
    /** {@inheritDoc} */
    public void createValueObject() throws HostException {
        /* Since this complex binding has a constructor that takes a
         * Value object, we might already have a Value object that
         * was not used yet. */
        if (mUnusedValueObject && mValueObject != null) {
            mUnusedValueObject = false;
            return;
        }
        mValueObject = mValueObjectFactory.createFiller12();
    }

    /** {@inheritDoc} */
    public void setChildrenValues() throws HostException {

         /* Make sure there is an associated Value object*/
        if (mValueObject == null) {
            createValueObject();
        }
        /* Get Value object property _lastTransDay */
        if (_log.isDebugEnabled()) {
            _log.debug("Getting value from Value object property "
                    + "_lastTransDay"
                    + " value=" + mValueObject.getLastTransDay());
        }
        _lastTransDay.setObjectValue(mValueObject.getLastTransDay());
        /* Get Value object property _filler14 */
        if (_log.isDebugEnabled()) {
            _log.debug("Getting value from Value object property "
                    + "_filler14"
                    + " value=" + mValueObject.getFiller14());
        }
        _filler14.setObjectValue(mValueObject.getFiller14());
        /* Get Value object property _lastTransMonth */
        if (_log.isDebugEnabled()) {
            _log.debug("Getting value from Value object property "
                    + "_lastTransMonth"
                    + " value=" + mValueObject.getLastTransMonth());
        }
        _lastTransMonth.setObjectValue(mValueObject.getLastTransMonth());
        /* Get Value object property _filler16 */
        if (_log.isDebugEnabled()) {
            _log.debug("Getting value from Value object property "
                    + "_filler16"
                    + " value=" + mValueObject.getFiller16());
        }
        _filler16.setObjectValue(mValueObject.getFiller16());
        /* Get Value object property _lastTransYear */
        if (_log.isDebugEnabled()) {
            _log.debug("Getting value from Value object property "
                    + "_lastTransYear"
                    + " value=" + mValueObject.getLastTransYear());
        }
        _lastTransYear.setObjectValue(mValueObject.getLastTransYear());
     }

    /** {@inheritDoc} */
    public void setPropertyValue(final int index) throws HostException {
 
        ICobolBinding child = getChildrenList().get(index);
        
       /* Children that are not bound to a value object are ignored.
        * This includes Choices and dynamically generated counters
        * for instance.  */
        if (!child.isBound()) {
            return;
        }
        
        /* Set the Value object property value from binding object */
        Object bindingValue = null;
        switch (index) {
        case 0:
            bindingValue = child.getObjectValue(String.class);
            mValueObject.setLastTransDay((String) bindingValue);
            break;
        case 1:
            bindingValue = child.getObjectValue(String.class);
            mValueObject.setFiller14((String) bindingValue);
            break;
        case 2:
            bindingValue = child.getObjectValue(String.class);
            mValueObject.setLastTransMonth((String) bindingValue);
            break;
        case 3:
            bindingValue = child.getObjectValue(String.class);
            mValueObject.setFiller16((String) bindingValue);
            break;
        case 4:
            bindingValue = child.getObjectValue(String.class);
            mValueObject.setLastTransYear((String) bindingValue);
            break;
         default:
            break;
        }
        if (_log.isDebugEnabled()) {
            _log.debug("Setting value of Value object property "
                    + child.getJaxbName()
                    + " value=" + bindingValue);
        }
    }

    /** {@inheritDoc} */
    public Object getObjectValue(
            final Class < ? > type) throws HostException {
        if (type.equals(Filler12.class)) {
            return mValueObject;
        } else {
            throw new HostException("Attempt to get binding " + getBindingName()
                    + " as an incompatible type " + type);
        }
    }

    /** {@inheritDoc} */
    public void setObjectValue(
            final Object bindingValue) throws HostException {
        if (bindingValue == null) {
            mValueObject = null;
            return;
        }
        if (bindingValue.getClass().equals(Filler12.class)) {
            mValueObject = (Filler12) bindingValue;
        } else {
            throw new HostException("Attempt to set binding " + getBindingName()
                    + " from an incompatible value " + bindingValue);
        }
    }

    /**
     * @return the java object factory for objects creation
     */
    public ObjectFactory getObjectFactory() {
        return mValueObjectFactory;
    }

    /**
     * @param valueObjectFactory the java object factory for objects creation 
     */
    public void setObjectFactory(final Object valueObjectFactory) {
        mValueObjectFactory = (ObjectFactory) valueObjectFactory;
    }

    /** {@inheritDoc} */
    public boolean isSet() {
        return (mValueObject != null);
    }

    /**
     * @return the bound Value object
     */
    public Filler12 getFiller12() {
        return mValueObject;
    }
    
}

