//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.21 at 02:08:09 PM CEST 
//


package com.legstar.test.coxb.tcobwvb;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.legstar.coxb.CobolElement;
import com.legstar.coxb.CobolType;


/**
 * <p>Java class for Filler12 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Filler12">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="lastTransDay">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="filler14">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="lastTransMonth">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="filler16">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="lastTransYear">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Filler12", propOrder = {
    "lastTransDay",
    "filler14",
    "lastTransMonth",
    "filler16",
    "lastTransYear"
})
public class Filler12
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    @CobolElement(cobolName = "LAST-TRANS-DAY", type = CobolType.ALPHANUMERIC_ITEM, levelNumber = 20, picture = "X(2)", srceLine = 13)
    protected String lastTransDay;
    @XmlElement(required = true)
    @CobolElement(cobolName = "FILLER", type = CobolType.ALPHANUMERIC_ITEM, levelNumber = 20, picture = "X", srceLine = 14)
    protected String filler14;
    @XmlElement(required = true)
    @CobolElement(cobolName = "LAST-TRANS-MONTH", type = CobolType.ALPHANUMERIC_ITEM, levelNumber = 20, picture = "X(2)", srceLine = 15)
    protected String lastTransMonth;
    @XmlElement(required = true)
    @CobolElement(cobolName = "FILLER", type = CobolType.ALPHANUMERIC_ITEM, levelNumber = 20, picture = "X", srceLine = 16)
    protected String filler16;
    @XmlElement(required = true)
    @CobolElement(cobolName = "LAST-TRANS-YEAR", type = CobolType.ALPHANUMERIC_ITEM, levelNumber = 20, picture = "X(2)", srceLine = 17)
    protected String lastTransYear;

    /**
     * Gets the value of the lastTransDay property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastTransDay() {
        return lastTransDay;
    }

    /**
     * Sets the value of the lastTransDay property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastTransDay(String value) {
        this.lastTransDay = value;
    }

    public boolean isSetLastTransDay() {
        return (this.lastTransDay!= null);
    }

    /**
     * Gets the value of the filler14 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFiller14() {
        return filler14;
    }

    /**
     * Sets the value of the filler14 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFiller14(String value) {
        this.filler14 = value;
    }

    public boolean isSetFiller14() {
        return (this.filler14 != null);
    }

    /**
     * Gets the value of the lastTransMonth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastTransMonth() {
        return lastTransMonth;
    }

    /**
     * Sets the value of the lastTransMonth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastTransMonth(String value) {
        this.lastTransMonth = value;
    }

    public boolean isSetLastTransMonth() {
        return (this.lastTransMonth!= null);
    }

    /**
     * Gets the value of the filler16 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFiller16() {
        return filler16;
    }

    /**
     * Sets the value of the filler16 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFiller16(String value) {
        this.filler16 = value;
    }

    public boolean isSetFiller16() {
        return (this.filler16 != null);
    }

    /**
     * Gets the value of the lastTransYear property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastTransYear() {
        return lastTransYear;
    }

    /**
     * Sets the value of the lastTransYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastTransYear(String value) {
        this.lastTransYear = value;
    }

    public boolean isSetLastTransYear() {
        return (this.lastTransYear!= null);
    }

}
