//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.21 at 02:08:09 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://coxb.test.legstar.com/tcobwvb", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.legstar.test.coxb.tcobwvb;
