//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.21 at 02:08:09 PM CEST 
//


package com.legstar.test.coxb.tcobwvb;

import java.io.Serializable;
import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.legstar.coxb.CobolElement;
import com.legstar.coxb.CobolType;


/**
 * <p>Java class for Transaction complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Transaction">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="lastTransDate">
 *             &lt;simpleType>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                 &lt;maxLength value="8"/>
 *               &lt;/restriction>
 *             &lt;/simpleType>
 *           &lt;/element>
 *           &lt;element name="filler12" type="{http://coxb.test.legstar.com/tcobwvb}Filler12"/>
 *         &lt;/choice>
 *         &lt;element name="lastTransAmount">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="15"/>
 *               &lt;fractionDigits value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="lastTransComment">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="9"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Transaction", propOrder = {
    "lastTransDate",
    "filler12",
    "lastTransAmount",
    "lastTransComment"
})
public class Transaction
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @CobolElement(cobolName = "LAST-TRANS-DATE", type = CobolType.ALPHANUMERIC_ITEM, levelNumber = 15, isRedefined = true, picture = "X(8)", srceLine = 11)
    protected String lastTransDate;
    @CobolElement(cobolName = "FILLER", type = CobolType.GROUP_ITEM, levelNumber = 15, redefines = "LAST-TRANS-DATE", srceLine = 12)
    protected Filler12 filler12;
    @XmlElement(required = true)
    @CobolElement(cobolName = "LAST-TRANS-AMOUNT", type = CobolType.PACKED_DECIMAL_ITEM, levelNumber = 15, isSigned = true, totalDigits = 15, fractionDigits = 2, picture = "S9(13)V99", usage = "PACKED-DECIMAL", srceLine = 18)
    protected BigDecimal lastTransAmount;
    @XmlElement(required = true)
    @CobolElement(cobolName = "LAST-TRANS-COMMENT", type = CobolType.ALPHANUMERIC_ITEM, levelNumber = 15, picture = "X(9)", srceLine = 19)
    protected String lastTransComment;

    /**
     * Gets the value of the lastTransDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastTransDate() {
        return lastTransDate;
    }

    /**
     * Sets the value of the lastTransDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastTransDate(String value) {
        this.lastTransDate = value;
    }

    public boolean isSetLastTransDate() {
        return (this.lastTransDate!= null);
    }

    /**
     * Gets the value of the filler12 property.
     * 
     * @return
     *     possible object is
     *     {@link Filler12 }
     *     
     */
    public Filler12 getFiller12() {
        return filler12;
    }

    /**
     * Sets the value of the filler12 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Filler12 }
     *     
     */
    public void setFiller12(Filler12 value) {
        this.filler12 = value;
    }

    public boolean isSetFiller12() {
        return (this.filler12 != null);
    }

    /**
     * Gets the value of the lastTransAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLastTransAmount() {
        return lastTransAmount;
    }

    /**
     * Sets the value of the lastTransAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLastTransAmount(BigDecimal value) {
        this.lastTransAmount = value;
    }

    public boolean isSetLastTransAmount() {
        return (this.lastTransAmount!= null);
    }

    /**
     * Gets the value of the lastTransComment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastTransComment() {
        return lastTransComment;
    }

    /**
     * Sets the value of the lastTransComment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastTransComment(String value) {
        this.lastTransComment = value;
    }

    public boolean isSetLastTransComment() {
        return (this.lastTransComment!= null);
    }

}
