//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.24 at 09:40:46 AM CEST 
//


package com.legstar.test.coxb.tcobwvb;

import java.io.Serializable;
import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.legstar.coxb.CobolElement;
import com.legstar.coxb.CobolType;


/**
 * <p>Java class for Transaction complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Transaction">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="transactionDate">
 *             &lt;simpleType>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                 &lt;maxLength value="8"/>
 *               &lt;/restriction>
 *             &lt;/simpleType>
 *           &lt;/element>
 *           &lt;element name="filler12" type="{http://coxb.test.legstar.com/tcobwvb}Filler12"/>
 *         &lt;/choice>
 *         &lt;element name="transactionAmount">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="15"/>
 *               &lt;fractionDigits value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="transactionComment">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="9"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Transaction", propOrder = {
    "transactionDate",
    "filler12",
    "transactionAmount",
    "transactionComment"
})
public class Transaction
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @CobolElement(cobolName = "TRANSACTION-DATE", type = CobolType.ALPHANUMERIC_ITEM, levelNumber = 15, isRedefined = true, picture = "X(8)", srceLine = 11)
    protected String transactionDate;
    @CobolElement(cobolName = "FILLER", type = CobolType.GROUP_ITEM, levelNumber = 15, redefines = "TRANSACTION-DATE", srceLine = 12)
    protected Filler12 filler12;
    @XmlElement(required = true)
    @CobolElement(cobolName = "TRANSACTION-AMOUNT", type = CobolType.PACKED_DECIMAL_ITEM, levelNumber = 15, isSigned = true, totalDigits = 15, fractionDigits = 2, picture = "S9(13)V99", usage = "PACKED-DECIMAL", srceLine = 18)
    protected BigDecimal transactionAmount;
    @XmlElement(required = true)
    @CobolElement(cobolName = "TRANSACTION-COMMENT", type = CobolType.ALPHANUMERIC_ITEM, levelNumber = 15, picture = "X(9)", srceLine = 19)
    protected String transactionComment;

    /**
     * Gets the value of the transactionDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionDate() {
        return transactionDate;
    }

    /**
     * Sets the value of the transactionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionDate(String value) {
        this.transactionDate = value;
    }

    public boolean isSetTransactionDate() {
        return (this.transactionDate!= null);
    }

    /**
     * Gets the value of the filler12 property.
     * 
     * @return
     *     possible object is
     *     {@link Filler12 }
     *     
     */
    public Filler12 getFiller12() {
        return filler12;
    }

    /**
     * Sets the value of the filler12 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Filler12 }
     *     
     */
    public void setFiller12(Filler12 value) {
        this.filler12 = value;
    }

    public boolean isSetFiller12() {
        return (this.filler12 != null);
    }

    /**
     * Gets the value of the transactionAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTransactionAmount() {
        return transactionAmount;
    }

    /**
     * Sets the value of the transactionAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTransactionAmount(BigDecimal value) {
        this.transactionAmount = value;
    }

    public boolean isSetTransactionAmount() {
        return (this.transactionAmount!= null);
    }

    /**
     * Gets the value of the transactionComment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionComment() {
        return transactionComment;
    }

    /**
     * Sets the value of the transactionComment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionComment(String value) {
        this.transactionComment = value;
    }

    public boolean isSetTransactionComment() {
        return (this.transactionComment!= null);
    }

}
